# Generated by Django 2.2.24 on 2021-10-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=6, unique=True)),
                ('upper_cap', models.IntegerField(default=1)),
                ('lower_cap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('upper_cap', models.IntegerField(default=1)),
                ('lower_cap', models.IntegerField(default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=8, unique=True)),
                ('upper_cap', models.IntegerField(default=1)),
                ('lower_cap', models.IntegerField(default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Instance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Academic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Admin')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Expert Knowledge'), (2, 'High Knowledge'), (3, 'Good Knowledge')], default=1)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Academic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Project')),
            ],
        ),
        migrations.AddField(
            model_name='academic',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.Instance'),
        ),
        migrations.AddField(
            model_name='academic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
