# Generated by Django 2.2.24 on 2021-12-16 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alloa_matching', '0003_auto_20211216_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Academic', 'Academic'), ('Admin', 'Admin')], default='Student', max_length=8)),
                ('unique_id', models.CharField(max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='academic',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alloa_matching.UserProfile'),
            preserve_default=False,
        ),
    ]
